openapi: 3.0.3
info:
  title: Product API
  version: 1.0.0
  description: API para manejar el CRUD de productos
paths:
  /products:
    get:
      summary: Obtener todos los productos
      operationId: getProducts
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Crear un nuevo producto
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Producto creado correctamente
  /products/{name}:
    put:
      summary: Actualizar producto
      operationId: updateProduct
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Producto actualizado correctamente
        '404':
          description: Producto no encontrado
    delete:
      summary: Eliminar producto
      operationId: deleteProduct
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Producto eliminado correctamente
        '404':
          description: Producto no encontrado
components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
          example: Laptop
        stock:
          type: integer
          example: 50
        price:
          type: number
          format: float
          example: 1299.99
      required:
        - name
        - stock
        - price